module.exports = {
  mode: 'jit',
  darkMode: false, // or 'media' or 'class'
  purge: {
    enabled: process.env.NODE_ENV === 'production',
    content: ['public/index.html', 'src/*.{js, jsx}', 'src/**/*.{js, jsx}'],
  },
  theme: {
    fontFamily: { sans: ['Inter'] },
    textColor: {
      primary_transparent: 'var(--color-primary-transparent)',
      primary_100: 'var(--color-primary-100)',
      primary_200: 'var(--color-primary-200)',
      primary_300: 'var(--color-primary-300)',
      primary_400: 'var(--color-primary-400)',
      primary_500: 'var(--color-primary-500)',
      primary_600: 'var(--color-primary-600)',
      primary_700: 'var(--color-primary-700)',
      primary_800: 'var(--color-primary-800)',
      primary_900: 'var(--color-primary-900)',
    },
    backgroundColor: {
      primary_transparent: 'var(--color-primary-transparent)',
      primary_100: 'var(--color-primary-100)',
      primary_200: 'var(--color-primary-200)',
      primary_300: 'var(--color-primary-300)',
      primary_400: 'var(--color-primary-400)',
      primary_500: 'var(--color-primary-500)',
      primary_600: 'var(--color-primary-600)',
      primary_700: 'var(--color-primary-700)',
      primary_800: 'var(--color-primary-800)',
      primary_900: 'var(--color-primary-900)',
    },
    ringColor: {
      primary_transparent: 'var(--color-primary-transparent)',
      primary_100: 'var(--color-primary-100)',
      primary_200: 'var(--color-primary-200)',
      primary_300: 'var(--color-primary-300)',
      primary_400: 'var(--color-primary-400)',
      primary_500: 'var(--color-primary-500)',
      primary_600: 'var(--color-primary-600)',
      primary_700: 'var(--color-primary-700)',
      primary_800: 'var(--color-primary-800)',
      primary_900: 'var(--color-primary-900)',
    },
    borderColor: {
      primary_transparent: 'var(--color-primary-transparent)',
      primary_100: 'var(--color-primary-100)',
      primary_200: 'var(--color-primary-200)',
      primary_300: 'var(--color-primary-300)',
      primary_400: 'var(--color-primary-400)',
      primary_500: 'var(--color-primary-500)',
      primary_600: 'var(--color-primary-600)',
      primary_700: 'var(--color-primary-700)',
      primary_800: 'var(--color-primary-800)',
      primary_900: 'var(--color-primary-900)',
    },
  },
  variants: {},
  plugins: [],
};
